apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-config-secret
    namespace: elasticsearch
type: Opaque
stringData:
    bootstrap.password: ENC[AES256_GCM,data:xyeVzKpOI+RU3BJquAdON2lkHAVmuQ==,iv:MGT0hg7SaZhsAeIn3qmhjAUSoWAbuui6eQUb1n4ZZOk=,tag:orrBHMEQcvHZAaj5rhL+RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://demo-aks-westeu-ad94.vault.azure.net
          name: sops-key
          version: 203e0278f0aa4d6f9b031563b237e4e1
          created_at: "2023-06-30T07:22:02Z"
          enc: CqnZysrQNjCav7h_o2fujcCpM8Wxhj-WDkz46Mho65nSDe9TQwQfZDXYDarNLnX4wuDsmSgheJoSdsX336CwMrKQfLlyNHMYDEAOW2242RjsUB6Duoryc26VwocP7RRHn5TjOfftMSXUNAgK_9D76-lhfVBwNCI2RrtRtq9Lr332lVceSJgVeuGsK6iaTjYpfN4HkCF9Ax4I2jANmVwe9847x_g8byR1tizsgydaKY1hvs4NEM-MrOx_bcPiP8jQuqjFHbVKs-u2axq1OXBQIOXpgw7tF_a5dYEoSDnFvd8YiyHtlsb5BTyJYPyNdgi0fGN7hxLaWmYMYzSRN-u5CQ
    hc_vault: []
    age: []
    lastmodified: "2023-06-30T07:22:02Z"
    mac: ENC[AES256_GCM,data:yuh/T8yMWExhLa/zzXslQoBiHEZB3tOG3FDCibNBYBiCpOtMLgYMxKaK/crC0qd7eRwvZSdO4QCb4q66Ov/t1Xlj8XwGhI5GDl+ZsPannhzUJrNxXc5aETw87P3H5OhGlUWT9drmpwwmasjRs/I3giJEkOgkF2a7uN2PU6Zpls8=,iv:fPzwsCPb6WjhQz3gH0bzSvLZHauDpmz+Ay/K8lbbMlo=,tag:rqqOLrvQ5KwGTyvfoaj5Yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
