apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-config-secret
    namespace: elasticsearch
type: Opaque
stringData:
    bootstrap.password: ENC[AES256_GCM,data:CHF1U7iAPfNY+t6pYboNSski9CW9V8rlErspUPoM,iv:TadQrAxvN7QkVLnLSCWrZW2B+2jMkgX2L5NmjTnRi8s=,tag:qDNI2XG9AZv8ap0In4XcsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://demo-aks-westeu-3248.vault.azure.net
          name: sops-key
          version: 49b347c5901d475284f27b9ef14f2afe
          created_at: "2023-06-05T08:17:09Z"
          enc: So_2LjJ4eT0Q7HMtOftAAnfh3hcLh2OTnCEwwoyxwCzPzad_SgDTlW1IAVw2dR97f8IJ6rvQR36RlVfzagYmEEN5DUD9Z-9vwysTJ7sexYSEvDeeUKgQuyt8RvueCYYLW1lW2Ox-NRobC80Sq09KSXzrhVSQG_MTKavAYElMBdjjeegLwvX2cdELyd9L00Qj0P9KxDHkqwBY3Fmi1WbU7gMtcc1lVgKYkfD3GS08TaKx--ccEt8CDm3YiP0ilFE7YM40oOIUU-PkaGqUV6a5WUENooE1EfkSVzpEcBGwmh7D32GpF_69zC-rcEH3kken-4JdYof9LZtBEBILM26smQ
    hc_vault: []
    age: []
    lastmodified: "2023-06-05T08:17:10Z"
    mac: ENC[AES256_GCM,data:d9yqA1Xt81twxJdsLvQoK0bNz9U7HONGPlpBguXQXn2qqjVogTqebjOlQc1eJx6GeNqwpbqikFKo43m8Zg2icU2qFRfxyKmo6HYXP+C9Wp0ibwFG1FRFt3biTMm3G3cyyRIFWArJPoIBkXjH+YLMSWRoKi1AbG7iFibPrtOxqEg=,iv:Vzi+ySbonwMXmJipNYH/WcaRQjJ8ja3wkuOJFay0Ims=,tag:C7wpuJH8ZpiMiL7BZ1R/eA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
