apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-config-secret
    namespace: elasticsearch
type: Opaque
stringData:
    bootstrap.password: ENC[AES256_GCM,data:I1YvDdWhZml1M3rWeFZ+lM4ith4ylX9zsafzWDuy,iv:RucpjCHemH4Kz1J1uNvvTTrpWDsWRkv9zFIAU1a+7Wc=,tag:KI6LYtyekl9Lm0nVjQWXMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://demo-aks-westeu-c65b.vault.azure.net
          name: sops-key
          version: 453d2f9a31914a9890241ec8de03d2fd
          created_at: "2023-06-19T13:54:01Z"
          enc: p5p9qctyUQ1BpURmduhgJtCMOnipG24Gr-i1fs2HWJUybzz3T8QrlsfdCaDsXhpW4zj_9258r3kVLHy5dSwtmFoyZMdQeMmgqX7gHCV2V_EA1VRm4owxelDuweCExJjPw789Oiid88umYDR_jcmpBDbBP6U6Y6TTQhq1rhNx0W-qkWmkZ_1XkNsDSs815z-unNL_L6d0nMyQ2RlvnZWHbIrAx0Z8hclc6ur9gvku7-dww7OrEsipU-uRQKoBWHSBKDLhH5COJdcnFtHtFAkD1cBKw2ZmaNTO9Q3a9CDscmcKEoJwR7k-C4mdT9uLrONkcjr3I4F3b4IPmGHVb6DWBg
    hc_vault: []
    age: []
    lastmodified: "2023-06-19T13:54:01Z"
    mac: ENC[AES256_GCM,data:m6JF9g13NxrYib9kdUxr0psadb99MVBx+tRbx7HlIi3r1YpzOPI396EUuV8WdN45lp1KY3oDk2PVQA5iStfEQbW9c/+taXZzLxcgrDlALXHA5KqvlceZixpzOxM3GsSooZzKsvfPgObrxyGEa9tPpbfcYpybtMiAWxcQWShLSOM=,iv:qhy62J1CcLInKqYaWLA5EHVSahddGX+0s08DUJkiw3o=,tag:bSRYjSbTUMoWjANM7W5lvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
